# Generated by Django 4.2.3 on 2023-07-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_recommendedproduct_searchquery_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='recommendedproduct',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='recommendedproduct',
            name='search_query',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.searchquery'),
        ),
    ]
